WebClientBot/Controllers/DialogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using WebClientBot.Models;

namespace WebClientBot.Controllers
{
    public class DialogController : Controller
    {
        static List<Question> queisions;
        static Dialog dialog;
        static Dictionary<Question, string> answers;
        // GET: Dialog
        [HttpGet]
        public ActionResult OpenDialog(int id)
        {
            if (dialog == null || dialog.Id != id)
                SetDialog(id);
            queisions = dialog == null ? null : queisions;
            answers = answers ?? new Dictionary<Question, string>();
            if (queisions != null && queisions.Count < dialog.Questions.Count)
                queisions.Add(GetNextQuestion(dialog.Questions.ToList(), queisions.Last()));

            queisions = queisions ?? new List<Question>() { dialog.Questions.FirstOrDefault() };
            ViewBag.Answers = answers;
            ViewBag.Flag = answers?.Count != dialog.Questions.Count;
            return View(queisions);
        }

        void SetDialog(int id)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            string adress = "/api/Dialogs/" + id;

            HttpResponseMessage response = client.GetAsync(adress).Result;


            if (response.IsSuccessStatusCode)
            {
                dialog = response.Content.ReadAsAsync<Dialog>().Result;
            }
            else
            {
                ViewBag.Error = "Error";
            }
            queisions = null;
            answers = null;
        }


        [HttpPost]
        public RedirectResult OpenDialog(string answer)
        {
            answers[queisions.Last()] = answer;
            return Redirect("/Dialog/OpenDialog/"+dialog.Id);
        }

        [HttpPost]
        public RedirectResult EndDialog()
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            foreach(KeyValuePair<Question,string> keyValue in answers)
            {
                QuestionsResult questionsResult = new QuestionsResult() { Question = keyValue.Key.Body,
                    Answer = keyValue.Value, DialogId = dialog.Id
                };
                HttpResponseMessage response = client.PostAsJsonAsync("api/QuestionsResults/",questionsResult).Result;
            }

            dialog = null;
            queisions = null;
            answers = null;

            return Redirect("/Dialog/BeforeDialog");
        }

        Question GetNextQuestion(List<Question> list,Question question)
        {
            bool flag = false;
            foreach(var q in list)
            {
                if (flag == true)
                    return q;
                flag = q.Id == question.Id;
            }
            return null;
        }

        [HttpPost]
        public ActionResult BeforeDialog(string Name)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = $"api/Dialogs?Name={Name}&Id=0";

            HttpResponseMessage response = client.GetAsync(adress).Result;

            Dialog res = null;
            if (response.IsSuccessStatusCode)
            {
                res = response.Content.ReadAsAsync<Dialog>().Result;

                return RedirectToAction("OpenDialog", new { id = res.Id });
            }
            else
            {
                ViewBag.result = "Error";
            }

            return View();
            

        }

        [HttpGet]
        public ActionResult BeforeDialog()
        {
            IsAutorized.autorized = false;
            return View();
        }

        public ActionResult Index()
        {

            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.GetAsync("api/Dialogs").Result;

            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<IEnumerable<Dialog>>().Result;
            }
            else
            {
                ViewBag.result = "Error";
            }
            return View();
        }

        public ActionResult Delete(int id)

        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Dialogs/" + id;

            HttpResponseMessage response = client.DeleteAsync(adress).Result;

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult VerifyAdmin(string login, string password)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = $"api/Doctors?login={login}&password={password}";

            HttpResponseMessage response = client.GetAsync(adress).Result;

            if (response.IsSuccessStatusCode)
            {
                IsAutorized.autorized = true;

                return RedirectToAction("Index");
            }

            return RedirectToAction("BeforeDialog");
        }

    }
}

WebClientBot/Controllers/QuestionsResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using WebClientBot.Models;

namespace WebClientBot.Controllers
{
    public class QuestionsResultsController : Controller
        {
            public ActionResult Index()
            {
                HttpClient client = new HttpClient();

                client.BaseAddress = new Uri(UrlContacts.BaseUrl);

                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("api/QuestionsResults").Result;

                if (response.IsSuccessStatusCode)
                {
                    ViewBag.result = response.Content.ReadAsAsync<IEnumerable<QuestionsResult>>().Result;
                }
                else
                {
                    ViewBag.result = "Error";
                }
                return View();
            }
            [HttpGet]
            public ActionResult Search()
            {

                return View("Index");
            }

            [HttpPost]
            public ActionResult Search(FormCollection fc)
            {
                HttpClient client = new HttpClient();

                client.BaseAddress = new Uri(UrlContacts.BaseUrl);

                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = client.GetAsync("api/QuestionsResults/" + fc["id"]).Result;

                if (response.IsSuccessStatusCode)
                {
                    ViewBag.result = response.Content.ReadAsAsync<Patient>().Result;
                }
                else
                {
                    ViewBag.result = "Error";
                }

                return View("Search");
            }

            public ActionResult Delete(int id)

            {
                HttpClient client = new HttpClient();

                client.BaseAddress = new Uri(UrlContacts.BaseUrl);

                client.DefaultRequestHeaders.Clear();

                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                string adress = "/api/QuestionsResults/" + id;

                HttpResponseMessage response = client.DeleteAsync(adress).Result;

                return RedirectToAction("Index");
            }

        //[HttpPost]
        //public ActionResult FindResultForName(string name)
        //{
        //    HttpClient client = new HttpClient();
        //    client.BaseAddress = new Uri(UrlContacts.BaseUrl);

        //    client.DefaultRequestHeaders.Clear();

        //    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        //    string adress = $"api/QuestionsResults?Name={name}&Id=0";

        //    HttpResponseMessage response = client.GetAsync(adress).Result;

        //    QuestionsResult res = null;
        //    if (response.IsSuccessStatusCode)
        //    {
        //        res = response.Content.ReadAsAsync<QuestionsResult>().Result;

        //        return RedirectToAction("Index");
        //    }

        //        ViewBag.result = "Error";

        //    return View(ViewBag);

        //}

    }
    }

WebClientBot/Views/Shared/DialogMaster.cshtml
@using WebClientBot.Models
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"> </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("PsyhoBot", "BeforeDialog", "Dialog", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (IsAutorized.autorized == true)
                    {
                    <li>@Html.ActionLink("Doctors", "Index", "Doctors", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Patients", "Index", "Patients", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Dialogs", "Index", "Dialog", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Questions", "Index", "Questions", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Answers", "Index", "Answers", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Results", "Index", "QuestionsResults", new { area = "" }, null)</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    @RenderBody()
</body>
</html>

WebClientBot/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>