WebClientBot/Models/Question.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace WebClientBot.Models
{
    [JsonObject(IsReference = true)]
    public class Question
    {
        public int Id { get; set; }
        public string Body { get; set; }

        public virtual ICollection<Dialog> Dialogs { get; set; }
        public Question()
        {
            Dialogs = new List<Dialog>();
            Answers = new List<Answer>();
        }

        public virtual ICollection<Answer> Answers { get; set; }
    }
}

WebClientBot/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using WebClientBot.Models;

namespace WebClientBot.Controllers
{
    public class QuestionsController : Controller
    {
        // GET: Questions
        public ActionResult Index()
        {

            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.GetAsync("api/Questions").Result;

            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<IEnumerable<Question>>().Result;
            }
            else
            {
                ViewBag.result = "Error";
            }
            return View();
        }

        [HttpGet]
        public ActionResult Add(int id = 0)
        {

            return View(new Question());
        }
        [HttpPost]
        public ActionResult Add(Question que)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.PostAsJsonAsync("api/Questions", que).Result;

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)

        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Questions/" + id;

            HttpResponseMessage response = client.DeleteAsync(adress).Result;

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Questions/" + id;

            HttpResponseMessage response = client.GetAsync(adress).Result;

            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<Question>().Result;
            }
            else
            {
                ViewBag.result = "Error";
            }

            return View("Edit");
        }


        [HttpPost]
        public ActionResult Edit(int id, Question que)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Questions/" + id;

            HttpResponseMessage response = client.PutAsJsonAsync(adress, que).Result;

            return RedirectToAction("Index");

        }
    }
}

WebClientBot/Views/Questions/Add.cshtml
@model WebClientBot.Models.Question
@{
    ViewBag.Title = "Add";
}
<br />
<br />
<br />
<div class="form-horizontal">

    <div class="row">
        <div class="col-sm-6 col-lg-offset-3">
            @using (Html.BeginForm())
            {
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Body, new { @class = "col-md-2 col-md-offset-2 control-label" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    @Html.ValidationMessageFor(model => model.Body)
                </div>

                <div class="row">
                    <div class="col-md-4 col-lg-offset-4">
                        <center><input type="submit" value="Submit" class="btn btn-info" />
                        <input type="reset" value="Reset" class="btn btn-warning" /></center>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

WebClientBot/Views/Questions/Edit.cshtml
@model WebClientBot.Models.Question
@{
    ViewBag.Title = "Edit";
}
<br />
<br />
<br />
<div class="form-horizontal">
    <div class="col-sm-6 col-lg-offset-3">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Body, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    @Html.ValidationMessageFor(model => model.Body)
                </div>

            <div class="form-group">
                <center><input type="submit" value="Submit" class="btn btn-info" />
                <input type="reset" value="Reset" class="btn btn-warning" /></center>
            </div>
        }
    </div>

WebClientBot/Views/Questions/Index.cshtml
<br />
<br />
<br />
<center>@Html.ActionLink("Add Question", "Add", "Questions", new { @class = "btn btn-success btn-lg" })</center>
<br />
<table class="table table-hover">
    <tr>
        <th class="active">ID</th>
        <th class="active">Body</th>
        <th class="active"></th>
        <th class="active"></th>
    </tr>
    @foreach (var que in ViewBag.result)
    {
        <tr>
            <th>@que.Id</th>
            <th>@que.Body</th>
            <th>
                @using (@Html.BeginForm("Delete", "Questions", FormMethod.Post))
                {
                    <input type="hidden" name="id" value="@que.Id" />
                    <input type="submit" value="Delete" class="btn btn-danger" />
                }
            </th>
            <th>
                @using (Html.BeginForm("Edit", "Questions", FormMethod.Get))
                {
                    <input type="hidden" name="id" value="@que.Id" />
                    <input type="submit" value="Edit" class="btn btn-info" />
                }
            </th>
        </tr>
    }
</table>
<br />