WebClientBot/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace WebClientBot.Models
{
    [JsonObject(IsReference = true)]
    public class Doctor
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Sex { get; set; }
        public DateTime Birthday { get; set; }
        public string Category { get; set; }
        public string Charasteristic { get; set; }

        public virtual ICollection<Patient> Patients { get; set; }
        public Doctor()
        {
            Patients = new List<Patient>();
        }
    }
}

WebClientBot/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using WebClientBot.Models;

namespace WebClientBot.Controllers
{
    public class DoctorsController : Controller
    {
        public ActionResult Index()
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.GetAsync("api/Doctors").Result;

            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<IEnumerable<Doctor>>().Result;
            }
            else
            {
                ViewBag.result = "Error";
            }
            return View();
        }

        [HttpGet]
        public ActionResult Add(int id = 0)
        {

            return View(new Doctor());
        }

        [HttpPost]
        public ActionResult Add(Doctor doc)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.PostAsJsonAsync("api/Doctors", doc).Result;

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)

        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Doctors/" + id;

            HttpResponseMessage response = client.DeleteAsync(adress).Result;

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Doctors/" + id;

            HttpResponseMessage response = client.GetAsync(adress).Result;

            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<Doctor>().Result;
            }
            else
            {
                ViewBag.result = "Error";
            }

            return View("Edit");
        }

        [HttpPost]
        public ActionResult Edit(int id, Doctor doc)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Doctors/" + id;

            HttpResponseMessage response = client.PutAsJsonAsync(adress, doc).Result;

            return RedirectToAction("Index");

        }

    }
}

WebClientBot/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using WebClientBot.Models;

namespace WebClientBot.Controllers
{
    public class PatientsController : Controller
    {



        public ActionResult Index()
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.GetAsync("api/Patients").Result;

            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<IEnumerable<Patient>>().Result;
            }
            else
            {
                ViewBag.result = "Error";
            }
            return View();
        }
        [HttpGet]
        public ActionResult Search()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Search(FormCollection fc)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.GetAsync("api/Patients/" +fc["id"]).Result;

            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<Patient>().Result;
            }
            else
            {
                ViewBag.result = "Error";
            }

            return View("Search");
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {

            return View(new Patient());
        }
        [HttpPost]
        public ActionResult AddOrEdit(Patient pat)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.PostAsJsonAsync("api/Patients", pat).Result;

            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Delete(int id)
        
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Patients/" + id;

            HttpResponseMessage response = client.DeleteAsync(adress).Result;

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Patients/" + id;

            HttpResponseMessage response = client.GetAsync(adress).Result;

            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<Patient>().Result;
            }
            else
            {
                ViewBag.result = "Error";
            }

            return View("Edit");
        }


        [HttpPost]
        public ActionResult Edit(int id, Patient pat)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Patients/" + id;

            HttpResponseMessage response = client.PutAsJsonAsync(adress, pat).Result;

            return RedirectToAction("Index");

        }

        //public ActionResult FindIdforName(string name)
        //{
        //    HttpClient client = new HttpClient();

        //    client.BaseAddress = new Uri(UrlContacts.BaseUrl);

        //    client.DefaultRequestHeaders.Clear();

        //    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        //    string adress = "api/Patients/GetPatientName/" + name;

        //    HttpResponseMessage response = client.GetAsync(adress).Result;


        //}

        //public ViewResult ViewDelete()
        //{
        //    return View(new Patient());
        //}
    }
}

WebClientBot/Views/Doctors/Add.cshtml
@model WebClientBot.Models.Doctor
@{
    ViewBag.Title = "Add";
}
<br />
<br />
<br />
<div class="form-horizontal">
    <div class="col-sm-6 col-lg-offset-3">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.FullName, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    @Html.ValidationMessageFor(model => model.FullName)
                </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Birthday, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                    @Html.ValidationMessageFor(model => model.Birthday)
                </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Sex, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Sex, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                    @Html.ValidationMessageFor(model => model.Sex)
                </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Category, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                    @Html.ValidationMessageFor(model => model.Category)
                </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Charasteristic, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Charasteristic, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                    @Html.ValidationMessageFor(model => model.Charasteristic)
                </div>

            <div class="form-group">
                <center><input type="submit" value="Submit" class="btn btn-info" />
                <input type="reset" value="Reset" class="btn btn-warning" /></center>
            </div>
        }
    </div>
    </div>

WebClientBot/Views/Doctors/Edit.cshtml
@model WebClientBot.Models.Doctor
@{
    ViewBag.Title = "Edit";
}
<br />
<br />
<br />
<div class="form-horizontal">
    <div class="col-sm-6 col-lg-offset-3">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.FullName, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    @Html.ValidationMessageFor(model => model.FullName)
                </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Birthday, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                    @Html.ValidationMessageFor(model => model.Birthday)
                </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sex, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Sex, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                    @Html.ValidationMessageFor(model => model.Sex)
                </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Category, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                    @Html.ValidationMessageFor(model => model.Category)
                </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Charasteristic, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Charasteristic, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                    @Html.ValidationMessageFor(model => model.Charasteristic)
                </div>

            <div class="form-group">
                <center><input type="submit" value="Submit" class="btn btn-info" />
                <input type="reset" value="Reset" class="btn btn-warning" /></center>
            </div>
        }
    </div>
</div>

WebClientBot/Views/Doctors/Index.cshtml
<br />
<br />
<br />
<center>@Html.ActionLink("Add Doctor", "Add", "Doctors", new { @class = "btn btn-success btn-lg" })</center>
<br />
<table class="table table-hover">
    <tr>
        <th class="active">ID</th>
        <th class="active">FullName</th>
        <th class="active">Birthday</th>
        <th class="active">Sex</th>
        <th class="active">Category</th>
        <th class="active">Characteristic</th>
        <th class="active"></th>
        <th class="active"></th>
    </tr>
    @foreach (var d in ViewBag.result)
    {
        <tr>
            <th>@d.Id</th>
            <th>@d.FullName</th>
            <th>@d.Birthday</th>
            <th>@d.Sex</th>
            <th>@d.Category</th>
            <th>@d.Charasteristic</th>
            <th>
                @using (@Html.BeginForm("Delete", "Patients", FormMethod.Post))
                {
                    <input type="hidden" name="id" value="@d.Id" />
                    <input type="submit" value="Delete" class="btn btn-danger" />
                }
            </th>
            <th>
                @using (Html.BeginForm("Edit", "Patients", FormMethod.Get))
                {
                    <input type="hidden" name="id" value="@d.Id" />
                    <input type="submit" value="Edit" class="btn btn-info" />
                }
            </th>
        </tr>
    }
</table>
<br />