WebClientBot/Models/Answer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace WebClientBot.Models
{
    [JsonObject(IsReference = true)]
    public class Answer
    {
        public int Id { get; set; }
        public string Body { get; set; }

        public int? QuestionId { get; set; }
        public Question Question { get; set; }
    }
}

WebClientBot/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using WebClientBot.Models;

namespace WebClientBot.Controllers
{
    public class AnswersController : Controller
    {
        // GET: Answers
        public ActionResult Index()
        {

            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.GetAsync("api/Answers").Result;

            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<IEnumerable<Answer>>().Result;
            }
            else
            {
                ViewBag.result = "Error";
            }
            return View();
        }

        [HttpGet]
        public ActionResult Add(int id = 0)
        {

            return View(new Answer());
        }
        [HttpPost]
        public ActionResult Add(Answer anw)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = client.PostAsJsonAsync("api/Answers", anw).Result;

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)

        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Answers/" + id;

            HttpResponseMessage response = client.DeleteAsync(adress).Result;

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Answers/" + id;

            HttpResponseMessage response = client.GetAsync(adress).Result;

            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<Answer>().Result;
            }
            else
            {
                ViewBag.result = "Error";
            }

            return View("Edit");
        }


        [HttpPost]
        public ActionResult Edit(int id, Answer anw)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri(UrlContacts.BaseUrl);

            client.DefaultRequestHeaders.Clear();

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            string adress = "/api/Answers/" + id;

            HttpResponseMessage response = client.PutAsJsonAsync(adress, anw).Result;

            return RedirectToAction("Index");

        }
    }
}

WebClientBot/Views/Answers/Add.cshtml
@model WebClientBot.Models.Answer
@{
    ViewBag.Title = "Add";
}
<br />
<br />
<br />
<div class="form-horizontal">
    <div class="col-sm-6 col-lg-offset-3">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Body, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    @Html.ValidationMessageFor(model => model.Body)
                </div>

            <div class="form-group">
                @Html.LabelFor(model => model.QuestionId, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.QuestionId, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                    @Html.ValidationMessageFor(model => model.QuestionId)
                </div>

            <div class="form-group">
                <center><input type="submit" value="Submit" class="btn btn-info" />
                <input type="reset" value="Reset" class="btn btn-warning" /></center>
            </div>
        }
    </div>
</div>

WebClientBot/Views/Answers/Edit.cshtml
@model WebClientBot.Models.Answer
@{
    ViewBag.Title = "Edit";
}
<br />
<br />
<br />
<div class="form-horizontal">
    <div class="col-sm-6 col-lg-offset-3">
        <p>Edit</p>
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Body, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    @Html.ValidationMessageFor(model => model.Body)
                </div>

            <div class="form-group">
                @Html.LabelFor(model => model.QuestionId, new { @class = "col-md-2 col-md-offset-2 control-label" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.QuestionId, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    @Html.ValidationMessageFor(model => model.QuestionId)
                </div>

            <div class="form-group">
                <center><input type="submit" value="Submit" class="btn btn-info" />
                <input type="reset" value="Reset" class="btn btn-warning" /></center>
            </div>
        }
    </div>

WebClientBot/Views/Answers/Index.cshtml
<br />
<br />
<br />
<center>@Html.ActionLink("Add Answer", "Add", "Answers", new { @class = "btn btn-success btn-lg" })</center>
<br />
<table class="table table-hover">
    <tr>
        <th class="active">ID</th>
        <th class="active">Body</th>
        <th class="active"></th>
        <th class="active"></th>
    </tr>
    @foreach (var anw in ViewBag.result)
    {
        <tr>
            <th>@anw.Id</th>
            <th>@anw.Body</th>
            <th>
                @using (@Html.BeginForm("Delete", "Answers", FormMethod.Post))
                {
                    <input type="hidden" name="id" value="@anw.Id" />
                    <input type="submit" value="Delete" class="btn btn-danger" />
                }
            </th>
            <th>
                @using (Html.BeginForm("Edit", "Answers", FormMethod.Get))
                {
                    <input type="hidden" name="id" value="@anw.Id" />
                    <input type="submit" value="Edit" class="btn btn-info" />
                }
            </th>
        </tr>
    }
</table>
<br />